### PR TITLE
update translations from lp, enable some new ones

### PR DESCRIPTION
**Pull request by mwhudson**
@xnox can you take a look?

There are also French, Spanish, Croatian and Asturian translations in here, I guess we should enable those too?

### CODE REVIEW

**Comment by vorlonofportland** [comment]
+1 on enabling the additional languages :)

**Comment by mwhudson** [comment]
> +1 on enabling the additional languages :)

OK, done!

**Comment by mwhudson** [comment]
[merge community translations of subiquity](https://trello.com/c/5WVkRKrB/872-merge-community-translations-of-subiquity)

**Comment by fitojb** [comment]
Hi, Spanish translator here. Can I maintain the translation here directly next time? For me, the less I have to use Launchpad Rosetta, the better.

**Comment by mwhudson** [comment]
> Hi, Spanish translator here. Can I maintain the translation here directly next time? For me, the less I have to use Launchpad Rosetta, the better.

Well in general I have no problem with that but I worry about coordinating with any other Spanish translators who come along. If you don't want to translate in LP you can still upload the .po file to LP too, right?

**Pull request merged**
