### PR TITLE
Focal sru

### PR DESCRIPTION
**Pull request by xnox**

### CODE REVIEW

**Comment by mwhudson** [comment]
This got uploaded, right?

**Comment by xnox** [comment]
> This got uploaded, right?

yes. But I am pondering if ~ubuntu-sru team prefers doing VCS reviews of SRUs or not.

**Comment by mwhudson** [comment]
I don't know where in the process the commit should land here. I guess when it is approved?

**Comment by mwhudson** [comment]
i.e. when it hits proposed

**Comment by vorlonofportland** [comment]
On May 6, 2020 5:54:35 PM PDT, Dimitri John Ledkov <notifications@github.com> wrote:
>> This got uploaded, right?
>
>yes. But I am pondering if ~ubuntu-sru team prefers doing VCS reviews
>of SRUs or not.

Definitely not, in the absence of a standardized workflow across all packages in the archive, and not with arbitrary merge targets.


-- 
Steve Langasek

**Pull request merged**
