### PR TITLE
exit console-conf immediately on a managed device

### PR DESCRIPTION
**Pull request by mwhudson**
I don't know if this is what we want, but I wanted to play with it so posting it up...

### CODE REVIEW

**Comment by cyphermox** [comment]
Yep, makes sense if it's indeed what we want, but then from the point where the device is managed, you couldn't run through network, keyboard, etc configuration. Seems slightly wrong, but it depends on what mvo and niemeyer will decide.

**Comment by mvo5** [comment]
https://github.com/snapcore/snapd/pull/2097 has landed so this is good to go.

**Comment by niemeyer** [comment]
Please note we'll probably (assuming nobody complains) tweak the name to "snap managed".

**Comment by niemeyer** [comment]
Also, the expectation from the code there is wrong, as far as the current PR is implemented.

**Comment by niemeyer** [comment]
snapcore/snapd#2102 is up for review. With that the logic there may be:
```
if snap managed -q; then
        ...
fi

**Comment by niemeyer** [comment]
Sorry, please hold fire on the above syntax. @pedronis makes a good point in the review.

**Pull request merged**
