### PR TITLE
enable sending reports to daisy

### PR DESCRIPTION
**Pull request by mwhudson**
Probably not really ready but might be interesting to play with. Will make a video tomorrow :)

### CODE REVIEW

**Comment by mwhudson** [comment]
I've fixed a few things here and there now and made some videos:

 * A UI crash: https://asciinema.org/a/oe6mVcPyNi2QGiTejY6cGiS5F (in the actual installer, the ui is restarted automatically)
 * An install failure: https://asciinema.org/a/C8eWjF3yD767D99stchuSf8dK
 * A device probe failure: https://asciinema.org/a/XD9GYiz1MzAmbTQYTyOn03c5B
 * A device _and_ disk probe failure: https://asciinema.org/a/8MrhWHGoTpBFmqVjzYxAV9oY4

**Comment by mwhudson** [comment]
> Does it need to be using bson?

Yes, the error reporter expects uploads as bson. To be fair, I just copied what whoopsie does for this, but looking into lp:daisy, I don't see any support for formats other than bson.

> Seems like it might be a better idea to use the json API from python core instead, unless you really specifically need to be using the APIs from bson. I think that would be a trivial change to; since you can still run json.load and whatnot.

I'd happily make this change if it would not break the whole feature :)

**Comment by matthewpaulthomas** [comment]
Sorry I didn’t get time to look at this again earlier. Nice work overall.

If I could change one thing, it would be the sentence “Select [C]ontinue to try again.” This is because “try again” could be referring to three different things: sending the error report again, saving the error report again, or (my assumption, though it’s not suggested anywhere in the UI!) performing the installation again. (A related problem is that the suggestion to “Select [C]ontinue” remains visible during the error report upload process when there is no Continue button to press.)

**Comment by mwhudson** [comment]
https://github.com/CanonicalLtd/subiquity/pull/583

**Pull request merged**
