### PR TITLE
refer to disks in the UI by id not path

### PR DESCRIPTION
**Pull request by mwhudson**
This is my effort at making a UI for the filesystem pages that (a) refers to disks by id (b) works in 80 characters-wide displays.

I really don't want to merge this without feedback, but what's the best way of getting feedback? Make a custom image and send it to the design team?

### CODE REVIEW

**Comment by gaughen** [comment]
I suggest taking some screen shots and send it to Design and the rest of us to have a look.

**Comment by mwhudson** [comment]
Here's an asciinema of me trying out the new UI: https://asciinema.org/a/0p8ln204bxwe230hptmdwo2cy

**Comment by mwhudson** [comment]
Is that enough for the design team or do we want screenshots as well?

**Comment by raharper** [comment]
On Tue, Apr 4, 2017 at 11:00 PM, Michael Hudson-Doyle <
notifications@github.com> wrote:

> Is that enough for the design team or do we want screenshots as well?
>

I suggest including just the screen shot of the disk selection page, with
this stuff


  DEVICE                                    SIZE        TYPE

    Hitachi_HDS5C3020ALA632_152D00539000-0:2     1.819T   local disk

      ADD FIRST PARTITION                  >

In the original design doc[1], there was a 'Show disk information' page
which included the details of the device
in case someone wanted to know what 'sda' was;


Looking at the UI, I'll posit that /dev/disk/by-id/* are generally not
user-friendly.
In some cases it's hard to distinguish a disk from another which it's the
same
manufacturer but only differs by portions of the serial string.


1. Once a few partitions have been created the device page might look like
this:

Partition, format and mount /dev/sda (the boot disk)

/dev/sda1               1Tb      ext4         /
/dev/sda2               120Gb    ext4         /var
/dev/sda3               16Gb     swap         SWAP
/dev/sda4               16Gb     btrfs        -
/dev/sda5               64Gb     -            -
FREE SPACE              720Gb

Add partition (max size 720Gb)                    .
Format, or create swap on, entire device (advanced)
Show disk information

Cancel
Done

Add partition, or select one to format and mount.

“Show disk information” opens a dialog with the output of “hdparm -i
/dev/sdX” for that device.

Partition, format and mount /dev/sda (the boot disk)

ATA device, with non-removable media

Model Number:       SAMSUNG SSD SM841 mSATA 512GB

Serial Number:      S132NYAD807740

Firmware Revision:  DXM43D0Q

Transport:          Serial, ATA8-AST, SATA 1.0a, SATA II Extensions, SATA
Rev 2.5, SATA Rev 2.6, SATA Rev 3.0

Standards:

Used: unknown (minor revision code 0x0039)

Supported: 9 8 7 6 5

Likely used: 9

Configuration:

Logical max current

cylinders 16383 16383

heads 16 16

sectors/track 63 63

--

CHS current addressable sectors:   16514064

LBA    user addressable sectors:  268435455

LBA48  user addressable sectors: 1000215216

Logical  Sector size:                   512 bytes

Physical Sector size:                   512 bytes

Logical Sector-0 offset:                  0 bytes

device size with M = 1024*1024:      488386 MBytes

device size with M = 1000*1000:      512110 MBytes (512 GB)

...

      Done                                            .

**Comment by mwhudson** [comment]
We talked about this in the subiquity call and decided to merge it, we can always iterate more.

**Pull request merged**
