### PR TITLE
Switch to core18

### PR DESCRIPTION
**Pull request by xnox**
because all the cool kids are switching this week too.

### CODE REVIEW

**Comment by xnox** [comment]
Ok this builds i think. Snaps will be available at https://launchpad.net/~xnox/+snap/subiquity soon

I guess it needs testing?

**Comment by mwhudson** [comment]
+1 assuming it works.

I wouldn't expect subtle failures tbh, if subiquity actually starts it's probably ok

**Comment by mwhudson** [comment]
Does this need to be coordinated with any livecd-rootfs changes?

**Comment by xnox** [comment]
> Does this need to be coordinated with any livecd-rootfs changes?

Well, we should switch if and when lxd switches. livecd-rootfs does the right thing.

**Comment by mwhudson** [comment]
OK, cool, I guess you are staying in touch with the relevant people?

I guess we should test upgrades from 18.04.4 before releasing this to stable. It should work fine but...

**Comment by xnox** [comment]
lxd changed, and so should we.

**Pull request merged**
