### PR TITLE
Barebones i18n setup.

### PR DESCRIPTION
**Pull request by xnox**
One can launch this in a UTF-8 encoding, e.g. LANG=C.UTF-8 switch language to Russian, cancel from the next screen and see that welcome screen has a Russian welcome message, switch to english again, cancel to return to the welcome screen and notice that welcome message is back in English.

So a general way to run subiquity for translation support is then this:
```
unset LANG LANGUAGE LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT LC_IDENTIFICATION LC_ALL
LANG=C.UTF-8 ./bin/subiquity-tui --dry-run
```
Since untranslated strings fallback to messageid which is English, I've also added a quick backdoor to spot untranslated strings / fixed width layout errors. It is called FAKE_TRANSLATE.

```
LANG=C.UTF-8 FAKE_TRANSLATE=1 ./bin/subiquity-tui --dry-run
```
With this, when selecting Russian all STRINGS will become _(STRINGS) to demote that they have been marked for translation. Anything without _() wrapper in the UI, is thus untranslatable.

Before rebase onto master, buttons did get translated.... but I guess they are somehow now pre-initialised, instead of executing _() function dynamically at runtime thus they end up having the language that was there before subiquity.i18n got imported and do not "refresh" upon `switch_language()` calls. I will work on fixing this up. Also, at least on my machine, the initial language selection correctly gets native label for russian - but not on the custom.iso will fix this up shortly.

Please review and merge this, such that we can setup translations in rosetta and start gathering translations.

### CODE REVIEW

**Comment by mwhudson** [comment]
This is awesome to see, thanks. Did you miss a step in your instructions though, I get "FileNotFoundError: [Errno 2] No translation file found for domain: 'subiquity'" when I try to run it.

It would perhaps be easier to review if the infrastructure was in one commit and putting _() in another but oh well. I'm just going to approve it anyway I expect :)

**Comment by mwhudson** [comment]
Oh yeah and console-conf will need to jam def _(x): return x into builtins, but otherwise should work?

**Comment by xnox** [comment]
`FileNotFoundError: [Errno 2] No translation file found for domain: 'subiquity'" when I try to run it.`

Please run `python3 setup.py clean build` that will produce .mo files in the build-tree, and they will become usable (there is code to detect in-tree compiled translations)

**Comment by xnox** [comment]
console-conf in the top script should `import subiquitycore.i18n` or some such. Or it can do a manual call `gettext.install('subiquity')` not sure. How do I run console-conf and does it make sense to also localise?

**Comment by mwhudson** [comment]
> console-conf in the top script should import subiquitycore.i18n or some such. Or it can do a manual call gettext.install('subiquity') not sure. 

Either works I guess.

> How do I run console-conf 

You run console-conf by running ./bin/console-conf-tui instead of ./bin/subiquity-tui, that's all.

> and does it make sense to also localise?

Hm. IIUC Ubuntu Core is not in general localized for space reasons. But translating console-conf might be worth it nevertheless. Ask in the forum? :)

**Comment by mwhudson** [comment]
> Please run python3 setup.py clean build that will produce .mo files in the build-tree, and they will become usable (there is code to detect in-tree compiled translations)

Ah yes, thanks. Looks great now :)

**Pull request merged**
