### PR TITLE
proxy support

### PR DESCRIPTION
**Pull request by mwhudson**
A bit of a WIP, haven't tested it on a core image yet.

https://bugs.launchpad.net/ubuntu/+source/subiquity/+bug/1657254

### CODE REVIEW

**Comment by cyphermox** [comment]
This should go more in subiquitycore, and then called from console-conf. It's a generic enough concept that we'll need it in subiquity eventually.

**Comment by mwhudson** [comment]
Yes, you're probably right. subiquity will need to do different things with the supplied proxy data though, I think? (well, mostly just pass it through to curtin?)

**Comment by mwhudson** [comment]
Turns out /etc/environment isn't writable in core anyway https://forum.snapcraft.io/t/set-proxy-via-snap-set-core-proxy-http/467 so this probably needs to wait until that is sorted out (I guess we could create a drop-in file for now but that's not a great answer)

**Comment by smoser** [comment]
http proxy is really just more complex than people initially think.  You almost never want to set it in /etc/environment.  At first it seems like it works, but then later it just causes more problems.   See my comment at https://bugs.launchpad.net/ubuntu/+source/maas/+bug/1671320/comments/1 for more information.

**Comment by xnox** [comment]
Meanwhile, over at curtin I see top-level proxy dictinary with multiple keys. Sould we not support all three like in curtin and pass it to it, somehow? http://bazaar.launchpad.net/~curtin-dev/curtin/trunk/revision/508

**Comment by xnox** [comment]
proxy support was merged already no....? should this be closed.

**Comment by mwhudson** [comment]
I think this aaaannccient PR is for console-conf?

**Comment by xnox** [comment]
Ah, console-conf.

**Comment by mwhudson** [comment]
Closing ancient pull requests.

**Pull request closed without merging**
