### PR TITLE
add user to the correct set of default groups

### PR DESCRIPTION
**Pull request by mwhudson**
It's not pretty but it does work!

For https://bugs.launchpad.net/subiquity/+bug/1722574

### CODE REVIEW

**Comment by cyphermox** [comment]
Ack

**Comment by xnox** [comment]
why is this not in `curtin` itself?

**Comment by mwhudson** [comment]
Curtin has no support for configuring users at all, what subiquity does is
configure cloud-init to create users on boot (cloud-init has a manually
maintained copy of this list too, but I wasn't sure how to make use of
that). This is frankly a bit shit and probably once we can get curtin to
leave the family mounted we should just call chroot /target adduser etc etc.

**Comment by xnox** [comment]
@smoser is there a way to specify to cloud-init to create an "admin" user with default set of groups that it means, i.e. passwd default set + sudo? or some such.

**Comment by smoser** [comment]
xnox there isnt a way to reference the default set of groups for cloud-init.

**Pull request merged**
