### PR TITLE
Basic zdev view

### PR DESCRIPTION
**Pull request by xnox**
TODO: allow to operate on "built-in" objects in dry-run mode
TODO: skip the screen on !s390x in real mode
TODO: add a lot more actions, as per spec

This is usable to enable/disable devices, if you managed to boot an LPAR zVM with subiquity.
A bit useless on KVM, as all devices should be activated there by default.

Did not run this with dasd passthrough... not sure if needs activation in that case or not.

Also doesn't integrate with preseeded answers stuff (but not sure that's needed at all, given that in KVM all devices are always activated, one simply needs to push "continue" on s390x in that case).

Overall this is not ready to be merged yet.

### CODE REVIEW

**Comment by mwhudson** [comment]
Also you will need answers support to the extend of automatically pressing OK if answers are provided.

**Comment by xnox** [comment]
I was hoping to use ZdevModel in the future, to store the output from chzdev there _or_ store a dict of objects there to support `--dry-run --s390x` mode. But i'm not sure if i can about providing fake experience there. I do need to extend this for answers.... however there is no answers to use in qemu/kvm as one can only really do things with these devices on lpar/zvm only.

I guess I at least need to do "go to the next page" answers support.

Focus does jump.... yes, need to wire up focus location correctly.

**Comment by xnox** [comment]
Pushed Zdev key into ubuntu-test-cases-live-server, such that nothing breaks on s390x when this is merged.

**Comment by mwhudson** [comment]
I don't know if you saw my comments on IRC about this but the way this branch sets up the view is that there is single a huge tablepile inside the listbox. Switching to a tablelistbox with the rows directly inside it performs waaaaay better (there is currently no support for dynamically inserting/removing rows from a tablelistbox but this view as currently written doesn't need that feature -- and it wouldn't be hard to add if it turned out to be needed)

**Pull request merged**
